# Generated by Django 5.2.8 on 2025-11-16 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("data_nascimento", models.DateField()),
                ("endereco", models.CharField(blank=True, max_length=255)),
                ("data_matricula", models.DateField(auto_now_add=True)),
                ("alergias", models.TextField(blank=True)),
                ("restricoes_alimentares", models.TextField(blank=True)),
                ("medicamentos", models.TextField(blank=True)),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Feminino")],
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("apelido", models.CharField(blank=True, max_length=100)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Mensalidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referencia", models.CharField(max_length=20)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                ("vencimento", models.DateField()),
                ("pago", models.BooleanField(default=False)),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                (
                    "metodo_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pix", "Pix"),
                            ("boleto", "Boleto"),
                            ("cartao", "Cartão"),
                            ("dinheiro", "Dinheiro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.aluno"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanoFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_mensalidade",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "desconto_percentual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "desconto_valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "tipo_pagamento",
                    models.CharField(
                        choices=[("mensal", "Mensal"), ("anual", "Anual")],
                        max_length=20,
                    ),
                ),
                (
                    "modalidade",
                    models.CharField(
                        choices=[
                            ("integral", "Integral"),
                            ("meio_periodo", "Meio período"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "aluno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plano_financeiro",
                        to="core.aluno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Responsavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("endereco", models.CharField(blank=True, max_length=255)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsaveis",
                        to="core.aluno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResponsavelFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financeiro_responsavel",
                        to="core.aluno",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.responsavel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nome", models.CharField(max_length=100)),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.professor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("conteudo", models.TextField()),
                ("atividades", models.TextField(blank=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "disciplina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.disciplina",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.professor",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.turma"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aluno",
            name="turma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.turma",
            ),
        ),
    ]
